CoverNation/Models/Administrator.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace CoverNation.Models
{
    [Table("Administrators")]
    public class Administrator:User
    {
        public string temp { get; set; }
        public int nesto2 { get; set; }
    }
}

CoverNation/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoverNation.ViewModel;
using CoverNation.DAL;
using CoverNation.Models;
using CoverNation.Helper;

namespace CoverNation.Controllers
{
    public class AdministratorController : Controller
    {
        CNContext db = new CNContext();
        // GET: Administrator
        public ActionResult Index(int id)
        {
            ProfileViewModel model = new ProfileViewModel();
            model = db.Users.Where(x => x.UserId == id)
                         .Select(x => new ProfileViewModel
                         {
                             UserId = x.UserId,
                             FirstName = x.FirstName,
                             LastName = x.LastName,
                             Username = x.Username,
                             ProfilePictureURL = x.ProfilePictureURL,
                             Role = "Admin",
                             IsVisitor = model.IsVisitor,
                             TypeOfVisitingUser = "Admin"

                         }).FirstOrDefault();
          
            return View("Profile", model);
        }
        public ActionResult DeleteGenre(int id)
        {
            Genre u = db.Genres.Where(x => x.GenreId == id).FirstOrDefault();
            db.Genres.Remove(u);
            db.SaveChanges();
            return RedirectToAction("ShowGenres");
        }
        public ActionResult ShowGenres()
        {
            GenreIndexVM model = new GenreIndexVM
            {
               GenresList = db.Genres.Select(x => new GenreRow()
                {
                    GenreId = x.GenreId,
                    GenreName = x.GenreName,
                    GenreImage = x.GenreImage
                }).ToList()
        };
   
            return View("ShowGenres", model);
    }
    [HttpGet]
        public ActionResult AddGenre()
        {
            GenreViewModel model = new GenreViewModel
            {
                GenreList = db.Genres.ToList()
            };
            return View("AddGenre", model);
        }
    [HttpPost]
        public ActionResult AddGenre(GenreViewModel vm)
        {
            Genre genre;
            if (vm.GenreId == 0)
            {
                genre = new Genre();
                db.Genres.Add(genre);
            }
            else
            {
                genre = db.Genres.Find(vm.GenreId);
            }
            genre.GenreId = vm.GenreId;
            genre.GenreName = vm.GenreName.ToString();
            genre.GenreImage = vm.GenreImage.ToString();
            db.SaveChanges();
            return RedirectToAction("ShowGenres");
        }
        public ActionResult EditGenre(int id)
        {
            GenreViewModel model = db.Genres.Where(x => x.GenreId == id).Select(f => new GenreViewModel
            {
                GenreId = f.GenreId,
                GenreName = f.GenreName,
                GenreImage = f.GenreImage,
                GenreList = db.Genres.ToList()
            }).Single();
            return View("AddGenre", model);
        }
    }
}

CoverNation/Views/Administrator/AddGenre.cshtml
@using CoverNation.ViewModel
@model CoverNation.ViewModel.GenreViewModel

<h2>Add Genre</h2>

@using (@Html.BeginForm("AddGenre", "Administrator", FormMethod.Post, new { @class = "form-horizontal" }))
{ 
@Html.HiddenFor(x => x.GenreId);
<div class="form-group">
    <label class="col-sm-2 control-label">Genre Name: </label>
    @Html.TextBoxFor(x => x.GenreName, new { @class = "form-control" })
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Genre Image: </label>
    @Html.TextBoxFor(x => x.GenreImage, new { @class = "form-control" })
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Save" class="btn btn-success" />
    </div>
</div>
}

CoverNation/Views/Administrator/Profile.cshtml
@model CoverNation.ViewModel.ProfileViewModel
@using CoverNation.Helper

@{
    ViewBag.Title = "Profile";
}
<style>
    .test {
        width: 150px;
        height: 150px;
    }
</style>
<h2>Profile</h2>

<h2>Dobrodošli, Admin - @Model.FirstName </h2>
@if (!Model.IsVisitor)
{
    <button>Izmjeni</button>
}
else
{
    <button>Ne mozes</button>
}
<br /><br />
@Html.ActionLink("Add Genre", "AddGenre", "Administrator", new { @class = "btn btn-primary" })

CoverNation/Views/Administrator/ShowGenres.cshtml
@using CoverNation.ViewModel
@model CoverNation.ViewModel.GenreIndexVM

<h2>Show Genres</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Genre ID</th>
            <th>Genre Name</th>
            <th>Genre Image</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (GenreRow x in Model.GenresList)
        {
            <tr>
                <td>@x.GenreId</td>
                <td>@x.GenreName</td>
                <td>@x.GenreImage</td>
               <td>
                    @Html.ActionLink("Edit Genre", "EditGenre", new { id = x.GenreId }, new { @class = "btn btn-success" })
                    @Html.ActionLink("Delete Genre", "DeleteGenre", new { id = x.GenreId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.ActionLink("Add New Genre", "AddGenre",new { }, new { @class = "btn btn-primary" })