CoverNation/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CoverNation.Models
{
    public class Comment
    {
        [Key]
        public int CommentId { get; set; }
        public int CoverId { get; set; }
        public Cover Cover { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
        public string CommentText { get; set; }
        public DateTime Date { get; set; }
    }
}

CoverNation/Controllers/CoverManagmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoverNation.Models;
using CoverNation.ViewModel;
using CoverNation.DAL;
using CoverNation.Helper;
using System.Threading.Tasks;
using static CoverNation.ViewModel.CoverManagmentViewModel;

namespace CoverNation.Controllers
{
    public class CoverManagmentController : Controller
    {
        CNContext db = new CNContext();

        public ActionResult GetCover(int coverId)
        {
            User user = db.Users.Find(Authentification.logedUser.UserId);
            int currentUserId = user.UserId;
            Cover cover = db.Covers.Find(coverId);
            var likes = db.Likes.Where(x => x.CoverId == cover.CoverId);
            CoverManagmentViewModel.CoverShow novi =
                new CoverManagmentViewModel.CoverShow
                {
                    CoverId = cover.CoverId,
                    CoverName = cover.CoverName,
                    UploadDate = cover.DateOfPosting,
                    Thumbnail = cover.Thumbnail,
                    CoverMusicianProfile = user.ProfilePictureURL,
                    YTurl = cover.VideoURL,
                    IsLikedByCurrentUser = likes.FirstOrDefault(x => x.UserId == currentUserId) == null ? false : true,
                    CurrentUserRaiting = likes.FirstOrDefault(x => x.UserId == currentUserId).Raiting,
                    NumOfRaitings = likes.Count()
                };

            novi.CoverRaiting = likes.Sum(x => x.Raiting);
            novi.CoverRaitingAvg = Math.Round(likes.Average(x => x.Raiting), 2); ;


            return PartialView("_cover", novi);
        }


        public PartialViewResult getMusicianCovers(int ProfileToShowUserId, bool isVisitor, int? currentStep,string searchTerm ="")
        {
            User User = db.Users.FirstOrDefault(x=> x.UserId == Authentification.logedUser.UserId);
            User ProfileToShowUser = db.Users.FirstOrDefault(x=> x.UserId == ProfileToShowUserId);
            List<Cover> covers;
            if (searchTerm == "")
            {
                if (ProfileToShowUser != null && ProfileToShowUser.Role == Role.Musician)
                {
                    covers = db.Covers.Where(x => x.MusicianId == ProfileToShowUserId).ToList();
                }
                else
                {
                    covers = db.Likes.Where(x => x.UserId == ProfileToShowUserId).Select(x => x.Cover).ToList();
                }
            }
            else
            {
                covers = db.Covers.Where(x => x.CoverName.ToLower().StartsWith(searchTerm.ToLower())).ToList();
            }
            
            var Likes = db.Likes.ToList();
            int coversToTake = 8;

            if (currentStep == null)
            {
                covers = covers.Take(coversToTake).ToList();
            }
            else
            {
                covers = covers.OrderBy(x => x.CoverId).Skip((int)currentStep * coversToTake).Take(coversToTake).ToList();
            }

            CoverManagmentViewModel.CoverShowList data =
                new CoverManagmentViewModel.CoverShowList
                {
                    ProfileToShowUserId = ProfileToShowUserId,
                    IsVisitor = isVisitor,
                    TypeOfVisitingUser = User.Role.ToString(),
                    
                    CoverList = covers.Select(x => new CoverShow
                    {
                        CoverId = x.CoverId,
                        CoverName = x.CoverName,
                        Thumbnail = x.Thumbnail,
                        YTurl = x.VideoURL,
                        UploadDate = x.DateOfPosting,
                        CoverMusicianProfile = User.ProfilePictureURL
                    }).ToList()
                };
            foreach (var item in data.CoverList)
            {
                var l = Likes.Where(y => y.CoverId == item.CoverId).ToList();
                item.NumOfRaitings = l.Count();
                if (l.Count > 0)
                {
                    item.CoverRaiting = l.Sum(y => y.Raiting);
                    item.CoverRaitingAvg = Math.Round(l.Average(y => y.Raiting), 2);
                }
                else
                {
                    item.CoverRaiting = 0;
                }
                bool isLikedByCurrent = Likes.FirstOrDefault(y => y.CoverId == item.CoverId && y.UserId == User.UserId) == null ? false : true;
                item.IsLikedByCurrentUser = isLikedByCurrent;
                if (isLikedByCurrent)
                {
                    item.CurrentUserRaiting = Likes.FirstOrDefault(y => y.CoverId == item.CoverId && y.UserId == User.UserId).Raiting;
                }else
                {
                    item.CurrentUserRaiting = 0;
                }
             
            }
            if (currentStep == null)
            {
                return PartialView("_coversPartial", data);

            }
            else
            {
                return PartialView("_coversPartialScroll", data);
            }
        }

        public ActionResult Index()
        {
            CoverManagmentViewModel.CoverManagmentAddCover model = new CoverManagmentViewModel.CoverManagmentAddCover();

            model.GenresList = db.Genres.Select(x => new SelectListItem { Value = x.GenreId.ToString(), Text = x.GenreName }).ToList();
            return PartialView("_coverManagmentIndex", model);
        }

        public ActionResult CoverModal(CoverShow vm)
        {
            return PartialView("_modalShow", vm);
        }

        [HttpGet]
        public PartialViewResult AddCover()

        {
            CoverManagmentViewModel.CoverManagmentAddCover model = new CoverManagmentViewModel.CoverManagmentAddCover();

            model.GenresList = db.Genres.Select(x => new SelectListItem { Value = x.GenreId.ToString(), Text = x.GenreName }).ToList();
            ViewData["genreList"] = model.GenresList;

            return PartialView("_addCover", model);

        }

        [HttpPost]
        public ActionResult AddCover(CoverManagmentAddCover VM)
        {
            Cover newCover = new Cover();


            #region GetThumbnail
            string YTVideoId = VM.VideoURL.Substring(VM.VideoURL.IndexOf("watch?v=") + 8, 11);
            #endregion

            #region url to embed
            string embedLink = VM.VideoURL.Remove(24, (VM.VideoURL.Length - 24));
            embedLink += "embed/";
            embedLink += VM.VideoURL.Remove(0, 32);
            #endregion


            newCover.CoverName = VM.CoverName;
            newCover.GenreId = VM.GenreId;
            newCover.VideoURL = embedLink;
            newCover.DateOfPosting = DateTime.Now;
            newCover.MusicianId = Authentification.logedUser.UserId;
            newCover.Thumbnail = "http://img.youtube.com/vi/" + YTVideoId + "/mqdefault.jpg";

            ViewData["succesMessage"] = "You have successfully added cover";

            db.Covers.Add(newCover);
            db.SaveChanges();

            //Creating new viewModel cause of redirection to the partial view
            CoverManagmentViewModel.CoverManagmentAddCover vm = new CoverManagmentViewModel.CoverManagmentAddCover();
            VM.GenresList = db.Genres.Select(x => new SelectListItem { Value = x.GenreId.ToString(), Text = x.GenreName }).ToList();


            return PartialView("_addCover", VM);
        }

        public ActionResult DeleteCover()
        {
            return PartialView("_deleteCover", null);
        }

        [HttpPost]
        public ActionResult DeleteCover(int coverId)
        {
            Cover coverToDelete = db.Covers.Find(coverId);
            db.Covers.Remove(coverToDelete);

            //DELETE COVER FROM PLAYLIST
            CoversToPlaylist ctp = new CoversToPlaylist();
            Like coverLike = new Like();
            Comment coverComments = new Comment();
            foreach (var item in db.CoversToPlayLists.Where(x => x.CoverId == coverId))
            {
                ctp = item;
                db.CoversToPlayLists.Remove(ctp);
            }
            foreach (var item in db.Likes.Where(x => x.CoverId == coverId))
            {
                coverLike = item;
                db.Likes.Remove(coverLike);
            }
            foreach (var item in db.Comments.Where(x => x.CoverId == coverId))
            {
                coverComments = item;
                db.Comments.Remove(coverComments);
            }
            db.SaveChanges();
            ViewData["succesMessage"] = "You have successfully deleted cover";

            return PartialView("_deleteCover", null);
        }

        public ActionResult SearchCover(string searchTerm = "")
        {
            List<Cover> model = new List<Cover>();

            if (searchTerm == "")
            {
                model = db.Covers.ToList();
            }
            else
            {
                model = db.Covers.Where(x => x.CoverName.StartsWith(searchTerm)).ToList();
            }


            return PartialView("_deleteList", model);

        }

        public JsonResult GetCovers(string term)
        {
            var data = db.Covers.Where(y => y.CoverName.StartsWith(term)).Select(x => x.CoverName).ToList();

            return Json(data, JsonRequestBehavior.AllowGet);
        }


        public void RateCover(int Raiting, int CoverId)
        {
            int LogedUserId = Authentification.logedUser.UserId;
            Like Like = db.Likes.FirstOrDefault(x => x.CoverId == CoverId && x.UserId == LogedUserId);
            if (Like != null)
            {
                Like.Raiting = Raiting;
                db.SaveChanges();
            }
            else
            {
                Like = new Like();
                Like.UserId = LogedUserId;
                Like.CoverId = CoverId;
                Like.Raiting = Raiting;
                db.Likes.Add(Like);

CoverNation/Views/CoverManagment/_addCover.cshtml
@model CoverNation.ViewModel.CoverManagmentViewModel.CoverManagmentAddCover

@using (Ajax.BeginForm("AddCover", null, new AjaxOptions { UpdateTargetId = "coverManagmentContent", InsertionMode = InsertionMode.Replace, OnSuccess = "clearAddCoverFields()" }, new { autocomplete = "off" }))
{
    if (ViewData["succesMessage"] != null)
    {
        <span class="alert-success">@ViewData["succesMessage"]</span>
        <br />
    }

    <div class="CNMS-addCoverContainer">
        @Html.LabelFor(x => x.CoverName)
        @Html.TextBoxFor(x => x.CoverName, new { @class = "loginInput" })
        <br />
        @Html.LabelFor(x => x.VideoURL)
        @Html.TextBoxFor(x => x.VideoURL, new { @class = "loginInput" })
        <br />
        @Html.LabelFor(x => x.GenreId)
        @Html.DropDownListFor(x => x.GenreId, Model.GenresList, new { @class = "loginInput" })
        <br />
        <br />

        <input type="submit" class="submitBtn" />
    </div><!-- end of CNMS-addCoverContainer -->
}

CoverNation/Views/CoverManagment/_comment.cshtml
@model CoverNation.ViewModel.CoverManagmentViewModel.CoverCommentSection
    <div class="commentDiv">
        <div class="floatLeft commentPicture-container" >
            <img src="@Model.UserPictureURL" class="commentUserIcon floatLeft" />
        </div>
        <span class="commentUser">@Model.Username - </span>
        <span class="commentDate">@Model.Date</span>
        <p>@Model.Comment</p>
    </div>
   

CoverNation/Views/CoverManagment/_commentList.cshtml
@model CoverNation.ViewModel.CoverManagmentViewModel.CoverCommentSectionList

@foreach (var item in Model.CommentList)
{
    Html.RenderPartial("_comment", item); 
}

CoverNation/Views/CoverManagment/_coverManagmentIndex.cshtml
@model CoverNation.ViewModel.CoverManagmentViewModel.CoverManagmentAddCover
<div class="coverManagmentContainer col-md-12">
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 CMNavListContainer">
        @Ajax.ActionLink("Add cover", "AddCover", null, new AjaxOptions { UpdateTargetId = "coverManagmentContent" }, new { @class="coverManNavList target", id="addCoverBtn" })<br />
        @Ajax.ActionLink("Delete cover", "DeleteCover",null, new AjaxOptions { UpdateTargetId = "coverManagmentContent"}, new { @class = "coverManNavList" })
    </div>

    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9" id="coverManagmentContent"> 
        @{ Html.RenderPartial("_addCover", Model); }
    </div>

</div><!-- end of coverManagmentContainer -->

<script>
    var items = document.getElementsByClassName("coverManNavList");
    items[0].style.borderRight = "2px solid white";
    $(".coverManNavList").on("click", function () {        
        for (var i = 0; i < items.length; i++) {

            items[i].style.borderRight = "none";
            items[i].style.color = "white";
        }
        this.style.borderRight = "2px solid white";

    });
</script>

CoverNation/Views/CoverManagment/_deleteCover.cshtml
@using (Ajax.BeginForm("SearchCover", "CoverManagment", new AjaxOptions { UpdateTargetId = "coverDeleteSection", OnComplete = "setCoverVideoHeight()" }))
{
    if (ViewData["succesMessage"] != null)
    {
        <span class="alert-success">@ViewData["succesMessage"]</span>
        <br />
    }
    <div class="col-md-12">
        <label class="col-md-12">Search cover by name:  </label>
        <span class="col-xs-9 col-md-9">@Html.TextBox("searchTerm", null, new { id = "txtSearch", @class = "loginInput ", autocomplete = "off" })</span>
        <input type="submit" value="Search" class="col-cs-2 col-md-2 submitBtn floatRight" style="padding:0 10px;" />
    </div>
}
<div id="coverDeleteSection" style="overflow-y:auto;" class="col-xs-12 col-md-12">

</div>

CoverNation/Views/CoverManagment/_deleteList.cshtml
@model IEnumerable<CoverNation.Models.Cover>
@foreach (var item in Model)
{
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 videoContainer">
        <div class="coverVideo col-xs-5 col-sm-5 col-md-12 col-lg-12">
            @*<iframe id="coverVideo-mobile" src="@item.VideoURL"></iframe>*@
            <img src="@item.Thumbnail" alt="@item.CoverName" style="width:100%; height:auto;" />
        </div>
        <div class="coverVideoContent col-xs-7 col-sm-7 col-md-12 col-lg-12">
            <div>
                <span class="col-md-11">@item.CoverName</span>
                <a class="fa fa-times col-md-1 floatRight" data-ajax="true" data-ajax-method="POST" data-ajax-mode="replace" data-ajax-update="#coverManagmentContent" href="/CoverManagment/DeleteCover?coverId=@item.CoverId"></a>
            </div>
        </div>

    </div><!-- end of videoContainer -->
}