CoverNation/Models/User.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoverNation.Models
{
    [Table("Users")]
    public class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ProfilePictureURL { get; set; }
        public DateTime RegistrationDate { get; set; }
        public DateTime BirthDate { get; set; }
        public Gender Gender { get; set; }
        public Role Role { get; set; }
        public string Location { get; set; }
    }

    public enum Gender {
        Male = 1,
        Female = 2
    }

    public enum Role
    {
        Admin = 1,
        Musician = 2,
        Basic = 3
    }
}

CoverNation/Controllers/PlaylistController.cs
using CoverNation.DAL;
using CoverNation.Helper;
using CoverNation.Models;
using CoverNation.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoverNation.Controllers
{
    public class PlaylistController : Controller
    {
        CNContext db = new CNContext();
        public ActionResult Index(int? userId,string v = "")
        {
            int logedUserId = Authentification.logedUser.UserId;
            PlaylistViewModel.PlaylistViewModelIndexList vm = new PlaylistViewModel.PlaylistViewModelIndexList
            {
            };

            if (userId == null)
            {
                userId = logedUserId;
                vm.IsDeleteList = true;
            }
            else
            {
                if (userId != logedUserId)
                {
                    vm.IsVisitor = true;
                }
                else
                {
                    vm.IsVisitor = false;
                }
                vm.IsDeleteList = false;
            }

            vm.Playlists = db.Playlists.Where(x => x.UserId == userId).Select(x => new PlaylistViewModel.PlaylistViewModelIndex
            {
                PlaylistId = x.PlaylistId,
                PlaylistName = x.Title,
                PlaylistThumbnail = db.CoversToPlayLists.Where(y => y.PlaylistId == x.PlaylistId).Select(y => y.Cover.Thumbnail).FirstOrDefault(),
                NumberOfCovers = db.CoversToPlayLists.Where(y => y.PlaylistId == x.PlaylistId).Count()
            }).ToList();

            //THIS PART IS CHECKING IS CALL MADE FROM PROFILE OR COVER FEED 
            if (v == "")
            {
                return PartialView("_index", vm);
            }
            else
            {
                return PartialView("_coverFeedIndex", vm);
            }
        }

        public ActionResult Play(int playlistId)
        {
            List<Cover> coversFromPlaylist = db.CoversToPlayLists.Where(x => x.PlaylistId == playlistId).Select(y => y.Cover).ToList();

            PlaylistViewModel.ModalPlay vm =
                new PlaylistViewModel.ModalPlay
                {
                    PlaylistPlayContent = coversFromPlaylist.Select(x => new PlaylistViewModel.PlayIndex
                    {
                        CoverId = x.CoverId,
                        Thumbnail = x.Thumbnail
                    }).ToList()
                };
            return PartialView("_playlistPlay", vm);
        }
        public ActionResult PlaylistItemPlay(int coverId)
        {
            int currentUserId = Authentification.logedUser.UserId;
            Cover cover = db.Covers.Find(coverId);
            var likes = db.Likes.Where(x => x.CoverId == cover.CoverId);
            CoverManagmentViewModel.CoverShow novi =
                new CoverManagmentViewModel.CoverShow
                {
                    CoverId = cover.CoverId,
                    CoverName = cover.CoverName,
                    UploadDate = cover.DateOfPosting,
                    Thumbnail = cover.Thumbnail,
                    YTurl = cover.VideoURL,
                    IsLikedByCurrentUser = likes.FirstOrDefault(x => x.UserId == currentUserId) == null ? false : true,

                };
            if (novi.IsLikedByCurrentUser)
            {
                novi.CurrentUserRaiting = likes.FirstOrDefault(x => x.UserId == currentUserId).Raiting;
            }
            else
            {
                novi.CurrentUserRaiting = 0;
            }
            novi.CoverRaiting = likes.Sum(x => x.Raiting);
            novi.CoverRaitingAvg = likes.Average(x => x.Raiting);
            novi.NumOfRaitings = likes.Count();

            return PartialView("_modalShow", novi);
        }

        public ActionResult ManagmentIndex()
        {
            return PartialView("_playlistManagmentIndex");
        }

        public ActionResult AddNew()
        {
            return PartialView("_addNew");
        }

        [HttpPost]
        public ActionResult AddNew(string playlistName)
        {
            Playlist newPlaylist = new Playlist();
            newPlaylist.UserId = Authentification.logedUser.UserId;
            newPlaylist.Title = playlistName;
            newPlaylist.DateOfCreating = DateTime.Now;
            db.Playlists.Add(newPlaylist);
            db.SaveChanges();

            PlaylistViewModel.AddNewCover playlistNames =
                new PlaylistViewModel.AddNewCover
                {
                    PlaylistNames = db.Playlists.Select(x => new SelectListItem { Value = x.PlaylistId.ToString(), Text = x.Title }).ToList(),
                };



            return PartialView("_coverToNew", playlistNames);
        }

        public ActionResult SearchAllCovers(string searchTerm)
        {

            CoverManagmentViewModel.CoverShowList vm =
                new CoverManagmentViewModel.CoverShowList
                {
                    CoverList = db.Covers.Where(x => x.CoverName.ToLower().StartsWith(searchTerm.ToLower()))
                                  .Select(x => new CoverManagmentViewModel.CoverShow
                                  {
                                      CoverId = x.CoverId,
                                      CoverName = x.CoverName,
                                      Thumbnail = x.Thumbnail,
                                      UploadDate = x.DateOfPosting
                                  }).ToList()
                };

            return PartialView("_coverToPL", vm);
        }

        public ActionResult CoverToPlaylist()
        {
            int userId = Authentification.logedUser.UserId;
            PlaylistViewModel.AddNewCover playlistNames =
               new PlaylistViewModel.AddNewCover
               {
                   PlaylistNames = db.Playlists.Where(x=> x.UserId == userId).Select(x => new SelectListItem { Value = x.PlaylistId.ToString(), Text = x.Title }).ToList(),
               };
            return PartialView("_coverToNew", playlistNames);
        }


        [HttpPost]
        public string CoverToPlaylist(int coverId, int playlistId)
        {

            if (db.CoversToPlayLists.FirstOrDefault(x => x.PlaylistId == playlistId && x.CoverId == coverId) != null)
            {
                return "The cover you selected is already in playlist.";
            }

            CoversToPlaylist ctpl = new CoversToPlaylist();
            ctpl.CoverId = coverId;
            ctpl.PlaylistId = playlistId;
            db.CoversToPlayLists.Add(ctpl);

            db.SaveChanges();

            return "You have successfully added cover to the playlist.";
        }

        public ActionResult GetPlaylistCovers(int playlistId)
        {
            var covers = db.CoversToPlayLists.Where(x => x.PlaylistId == playlistId).Select(x => x.Cover);
            PlaylistViewModel.DeleteList vm =
                new PlaylistViewModel.DeleteList
                {
                    PlaylistId = playlistId,
                    CoverDeleteList = covers.Select(x => new CoverManagmentViewModel.CoverShow
                    {
                        CoverId = x.CoverId,
                        CoverName = x.CoverName,
                        Thumbnail = x.Thumbnail,
                        YTurl = x.VideoURL,
                        UploadDate = x.DateOfPosting,
                    }).ToList()
                };

            return PartialView("_deleteList", vm);
        }

        public ActionResult DeleteFromPlaylist(int coverId, int playlistId)
        {

            var ctpl = db.CoversToPlayLists.FirstOrDefault(x => x.PlaylistId == playlistId && x.CoverId == coverId);
            if (ctpl != null)
            {
                db.CoversToPlayLists.Remove(ctpl);
                db.SaveChanges();
            }

            return RedirectToAction("GetPlaylistCovers", new { playlistId = playlistId });
        }

        public ActionResult DeletePlaylist(int playlistId)
        {
            var ctpl = db.CoversToPlayLists.Where(x => x.PlaylistId == playlistId).ToList();
            db.CoversToPlayLists.RemoveRange(ctpl);

            db.Playlists.Remove(db.Playlists.Find(playlistId));
            db.SaveChanges();

            return RedirectToAction("Index");
        }


        public ActionResult PlaylistCoverSmallScreen(int playlistId)
        {
            int userId = Authentification.logedUser.UserId;
            int profileToShowUserId = db.Playlists.FirstOrDefault(x => x.PlaylistId == playlistId).UserId;
            var Likes = db.Likes.ToList();


            CoverManagmentViewModel.CoverShowList data =
                new CoverManagmentViewModel.CoverShowList
                {
                    ProfileToShowUserId = profileToShowUserId,
                    CoverList = db.CoversToPlayLists.Where(x => x.PlaylistId == playlistId).Select(x => x.Cover)
                                                    .Select(x => new CoverManagmentViewModel.CoverShow
                                                    {
                                                        CoverId = x.CoverId,
                                                        CoverName = x.CoverName,
                                                        Thumbnail = x.Thumbnail,
                                                        YTurl = x.VideoURL,
                                                        UploadDate = x.DateOfPosting,
                                                    }).ToList()
                };

            foreach (var item in data.CoverList)
            {
                var l = Likes.Where(y => y.CoverId == item.CoverId).ToList();
                item.NumOfRaitings = l.Count();
                if (l.Count > 0)
                {
                    item.CoverRaiting = l.Sum(y => y.Raiting);
                    item.CoverRaitingAvg = Math.Round(l.Average(y => y.Raiting), 2);
                }
                else
                {

CoverNation/Views/Users/Login.cshtml
@model CoverNation.ViewModel.LoginViewModel

@using (Html.BeginForm("Login", "Users", FormMethod.Post, new { autocomplete = "off" }))
{
    @Html.AntiForgeryToken()


        <div class="loginContainer">
            <span class="logoText">Cover Nation</span>
            <div class="formGroup">
                @Html.ValidationSummary(true, "", new { @class = "login-text-danger" })

                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "formLabel col-xs-12" })
                <div class="col-xs-12 col-md-10">
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "loginInput" } })
                    <div class="valMsgContainer">
                      @Html.ValidationMessageFor(model => model.Username, "", new { @class = "login-text-danger" }) 
                        @if (@Html.ValidationMessageFor(model => model.Username).ToHtmlString().Contains("required"))
                        {
                            <img src="~/Content/images/error-icon.png" class="errorImg" />
                        }
                    </div>
                </div>
            </div>
            <div class="formGroup">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "formLabel col-xs-12" })
                <div class="col-xs-12 col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "loginInput" } })
                    <div class="valMsgContainer">
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "login-text-danger" })
                        @if (@Html.ValidationMessageFor(model => model.Password).ToHtmlString().Contains("required"))
                        {
                            <img src="~/Content/images/error-icon.png" class="errorImg" />
                        }
                    </div>
                </div>
            </div>
            <div class="formGroup">
                <div class="col-xs-12 col-md-10">
                        @Html.CheckBoxFor(model => model.RemeberMe, htmlAttributes: new { @class = "remeberMeCheckBox" })
                        <span class="formLabel">Remeber me</span>
                        <input type="submit" value="Login" class="btn btn-default loginBtn"/>
                </div>
            </div>
        </div>
}

CoverNation/Views/Users/Profile.cshtml
@model CoverNation.ViewModel.ProfileViewModel
<div class="mainContainer">
    <div class="profileContainer">
        <span id="actionMessage"></span>
        <!--- /radi se -->
        <div class="profileHeaderContainer">
            <div class="profileHeaderContent">
                <div class="profileHeaderNavigation">
                    <a href="/CoverFeed/Index"><img alt="Logo" src="~/Content/images/covernation2.png" style="width:200px;height:auto;" /></a> 
                   <a href="/Users/Logout" style="color:white; text-decoration:none; float:right;"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a>
                </div><!-- end of profileHeaderTop-->

                <div class="profileHeaderBody">

                    <div class="profileHeaderBodyLeft floatLeft">

                        <img src="@Model.ProfilePictureURL" alt="Profile picture" class="profilePicture" />

                    </div><!-- end of profileHeaderBodyLeft -->

                    <div class="profileHeaderBodyMiddle floatLeft">

                        <div class="profileName floatLeft">
                            <span>@Model.FirstName @Model.LastName</span>
                            @if (Model.Role == "Musician" && Model.TypeOfVisitingUser == "BasicUser")
                            {
                                if (Model.IsSubscribed == false)
                                {
                                    @Ajax.ActionLink("+ Subscribe", "Subscribe", "Users", new { musicianId = Model.UserId }, new AjaxOptions { OnSuccess = "subscribeMsg" }, new { id = "SubscribeBtn", @class = "subscribeBtn-lg subBtn" })
                                }
                                else
                                {
                                    @Ajax.ActionLink("- Unsubscribe", "Subscribe", "Users", new { musicianId = Model.UserId }, new AjaxOptions { OnSuccess = "subscribeMsg" }, new { id = "UnsubscribeBtn", @class = "subscribeBtn-lg subBtn" })
                                }

                            }
                        </div><!-- end of profileName-->
                        <div class="infoIcons floatLeft">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-microphone" aria-hidden="true"></i>
                        </div><!-- end of infoIcon-->
                        <div class="infoIconsText floatLeft">
                            <span>Default</span>
                            <span>@Model.Subs</span>
                            <span>@Model.NumOfCovers</span>
                        </div><!-- end of infoIconsText -->
                    </div><!-- end of profileHeaderBodyLeft -->

                    <div class="profileHeaderBodyRight headerRight-lg floatLeft">
                        <ul>
                            <li>
                                @Ajax.ActionLink("COVERS", "getMusicianCovers", "CoverManagment", new { ProfileToShowUserId = Model.UserId }, new AjaxOptions
                           {
                               UpdateTargetId = "profileContentData",
                               OnBegin = "reload"
                           })
                            </li>
                            <li>
                                @Ajax.ActionLink("ABOUT", "About", "Users", new { userId = Model.UserId },
                               new AjaxOptions
                               {
                                   UpdateTargetId = "profileContentData",
                                   OnBegin = "onBegin",
                                   OnComplete = "onComplete"
                               })
                            </li>
                            <li>
                                @Ajax.ActionLink("PLAYLIST", "Index", "Playlist", new { userId = Model.UserId },
                               new AjaxOptions
                               {
                                   UpdateTargetId = "profileContentData",
                                   OnBegin = "onBegin",
                                   OnComplete = "onComplete"
                               })
                            </li>
                            @if (!Model.IsVisitor)
                            {
                                <li>@Html.ActionLink("SETTINGS", "Index", "CNMS")</li>
                            }
                        </ul>
                    </div><!-- end of profileHeaderBodyLeft -->
                </div><!-- end of profileHeaderBody -->
            </div><!-- end of headerNavigation -->
        </div><!-- end of profileHeaderContainer-->
        <div class="profileContent" id="profileContentContainer">
            <div class="headerRight-sm">
                <ul>
                    <li>
                        @Ajax.ActionLink("COVERS", "getMusicianCovers", "CoverManagment", new { ProfileToShowUserId = Model.UserId },
                        new AjaxOptions
                        {
                            UpdateTargetId = "profileContentData",
                            OnBegin = "reload"
                        })
                    </li>
                    <li>
                        @Ajax.ActionLink("ABOUT", "About", "Users", new { userId = Model.UserId },
                        new AjaxOptions
                        {
                            UpdateTargetId = "profileContentData",
                            OnBegin = "onBegin",
                            OnComplete = "onComplete"
                        })
                    </li>
                    <li>
                        @Ajax.ActionLink("PLAYLIST", "Index", "Playlist", new { userId = Model.UserId },
                        new AjaxOptions
                        {
                            UpdateTargetId = "profileContentData",
                            OnBegin = "onBegin",
                            OnComplete = "onComplete"
                        })
                    </li>
                    @if (!Model.IsVisitor)
                    {
                        <li>@Html.ActionLink("SETTINGS", "Index", "CNMS")</li>
                    }
                </ul>
            </div><!-- end of profileHeaderBodyLeft -->
            <div id="profileContentData" class="profileContentData">
                @{
                    Html.RenderAction("getMusicianCovers", "CoverManagment", new { ProfileToShowUserId = Model.UserId, isVisitor = Model.IsVisitor });
                }
            </div><!-- end od aboutMusicianContainer-->
        </div><!-- end of profileCoverContent -->
    </div><!-- end of profileContainer -->
</div>
<script>
    $(document).ready(function () {
        if ($(window).width() > 768) {
            $('.subBtn').addClass('subscribeBtn-lg').removeClass('subscribeBtn-sm');
        }
        else {
            $('.subBtn').addClass('subscribeBtn-sm').removeClass('subscribeBtn-lg');

        }
        var imgUrl = '"' + "@Model.ProfilePictureURL" + '"';
        var cssStyle = ".profileContainer:before { background-image: url(" + imgUrl + "); }";
        document.styleSheets[0].insertRule(cssStyle, 0);
    });
</script>

CoverNation/Views/Users/_about.cshtml
@model CoverNation.ViewModel.UserInfo.UserInfoViewModel
<div class="col-md-11 aboutUserContainer">
    <div class="col-md-6">
        <h3>Personal info</h3>
        <span class="col-xs-6 col-md-4">First name: </span>
        <span class="col-xs-6 col-md-8">@Model.FirstName</span>

        <span class="col-xs-6 col-md-4">Last name: </span>
        <span class="col-xs-6 col-md-8">@Model.LastName</span>

        <span class="col-xs-6 col-md-4">Email: </span>
        <span class="col-xs-6 col-md-8">@Model.Email</span>

        <span class="col-xs-6 col-md-4">Birth date: </span>
        <span class="col-xs-6 col-md-8">@Model.BirthDate</span>

        <span class="col-xs-6 col-md-4">Registration date: </span>
        <span class="col-xs-6 col-md-8">@Model.RegistrationDate</span>

        <span class="col-xs-6 col-md-4">Gender: </span>
        <span class="col-xs-6 col-md-8">@Model.Gender</span>

        @if (Model.UserType == "Musician")
            {
            <span class="col-md-12">Preferred genre: </span>
                <ul>
                    @foreach (var item in Model.PreferredGenres)
                    {
                        <li><b>@item.GenreName</b></li>
                    }
                </ul>
        }

    </div>
    @if (Model.UserType == "Musician")
    {

        <div class="col-md-6">
            <h3>Biography</h3>
            <span class="col-md-12">@Model.Biography</span>
        </div>
        
        <div class="col-md-11">
            <h3>Musician Education</h3>
            @foreach (var item in Model.MusicianEducation)
            {
                <div class="col-md-12">
                    <img src="@item.PictureURL"/>
                    <span>@item.Name</span>
                </div>
            }
        </div>
    }
    else
    {
        <div class="col-md-6">
            <span class="col-md-12">Preferred genre: </span>
            <ul>
                @foreach (var item in Model.PreferredGenres)
                {
                    <li><b>@item.GenreName</b></li>
                }
            </ul>

        </div>
    }

    <div class="col-md-11">
        <h3>Favourite artist</h3>

        @foreach (var item in Model.FavouriteArtists)
            {
            <div class="favouriteArtistSection col-xs-6 col-md-4" style="padding:10px;">
                <div class="col-xs-12 col-md-12">
                    <img class="favArtistImg" src="@item.ImageURL" style="width:100%; height:170px;" />
                </div>
                <div class="col-xs-12 col-md-12">
                    <h4>@item.Name</h4>
                    <p>@item.Description</p>
                </div>
            </div><!-- end of favouriteArtistSection -->
        }
    </div>

</div><!-- end of aboutUserContainer -->

CoverNation/Views/Users/_usersSearch.cshtml
@model CoverNation.ViewModel.UserInfo.UserSearch

<a href="/Users/Profile?id=@Model.UserId">
    <div class="row">
        <div class="col-md-12" id="result-row">
            <div class="row">
                <div class="col-md-3">
                    <div id="search-result-left">
                        <img src="@Model.ProfilePic" alt="User profile picture" />
                        <p>@Model.UserType</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div id="search-result-right">
                        <p>@Model.FirstName @Model.LastName</p>
                        <p>@Model.Username</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</a>

CoverNation/Views/Users/_usersSearchList.cshtml
@model CoverNation.ViewModel.UserInfo.UserSearchList

@foreach (var item in Model.SearchList)
{ 
    Html.RenderPartial("_usersSearch", item);   
}